#ddev-generated
parameters:
    app.redis.session.host: "%env(REDIS_SESSION_HOST)%"
    app.redis.session.port: "%env(int:REDIS_SESSION_PORT)%"
    app.redis.session.db: "%env(int:REDIS_SESSION_DB)%"

    app.redis.cache.dsn: "redis://%env(REDIS_CACHE_HOST)%:%env(int:REDIS_CACHE_PORT)%/%env(int:REDIS_CACHE_DB)%"
    app.redis.fpc.dsn: "redis://%env(REDIS_FPC_HOST)%:%env(int:REDIS_FPC_PORT)%/%env(int:REDIS_FPC_DB)%"

services:
    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                  - '%app.redis.session.host%'
                  - '%app.redis.session.port%'
            - method: select
              arguments:
                  - "%app.redis.session.db%"
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'

framework:
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        pools:
            cache.http:
                default_lifetime: "%env(int:SHOPWARE_HTTP_DEFAULT_TTL)%"
                adapter: cache.adapter.redis
                provider: "%app.redis.fpc.dsn%"
                tags: cache.tags
            cache.object:
                default_lifetime: 3600
                adapter: cache.adapter.redis
                tags: cache.tags
            cache.tags:
                default_lifetime: 3600
                adapter: cache.adapter.redis
            cache.serializer:
                adapter: cache.adapter.redis
            cache.annotations:
                adapter: cache.adapter.redis
            cache.property_info:
                adapter: cache.adapter.redis
            cache.messenger:
                adapter: cache.adapter.redis
            cache.property_access:
                adapter: cache.adapter.redis
        default_redis_provider: "%app.redis.cache.dsn%"
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

shopware:
    increment:
        user_activity:
            type: 'redis'
            config:
                url: "%app.redis.cache.dsn%"
        message_queue:
            type: 'redis'
            config:
                url: "%app.redis.cache.dsn%"
