#ddev-generated
version: '3.6'
services:
    redis:
        container_name: ddev-${DDEV_SITENAME}-redis
        image: redis:6
        # These labels ensure this service is discoverable by ddev.
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        volumes:
            - ".:/mnt/ddev_config"
            - "./redis:/usr/local/etc/redis"
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    web:
        environment:
            - REDIS_CACHE_HOST=redis
            - REDIS_CACHE_PORT=6379
            - REDIS_CACHE_DB=0
            - REDIS_SESSION_HOST=redis
            - REDIS_SESSION_PORT=6379
            - REDIS_SESSION_DB=2
            - REDIS_FPC_HOST=redis
            - REDIS_FPC_PORT=6379
            - REDIS_FPC_DB=1